header:
  version: 19

build_system: oe

defaults:
  repos:
    branch: scarthgap

repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    path: sources
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded
    path: sources/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:
      meta-webserver:
      meta-perl:

  meta-ros:
    url: https://github.com/ros/meta-ros
    path: sources/meta-ros
    layers:
      meta-ros-common:
      meta-ros2:
      meta-ros2-jazzy:

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi
    path: sources/meta-raspberrypi
    layers:
      .:

  meta-security:
    url: https://git.yoctoproject.org/git/meta-security
    path: sources/meta-security
    layers:
      .:

  meta-virtualization:
    url: https://git.yoctoproject.org/git/meta-virtualization
    path: sources/meta-virtualization
    layers:
      .:

  meta-rust-bin:
    url: https://github.com/rust-embedded/meta-rust-bin
    branch: master
    path: sources/meta-rust-bin
    layers:
      .:

  meta-rpilinux1:
    url: ssh://git@gitlab.com/vrion69/meta-rpilinux1
    branch: main
    path: sources/meta-rpilinux
    layers:
      .:
